import * as THREE from 'three';
import './style.css';

type Mode='tpp'|'fpp';
type Save={version:1;player:{x:number;y:number;z:number;ry:number;mode:Mode};camera:{yaw:number;pitch:number;distance:number};changes:Record<string,string[]>};
const SAVE_KEY='virtual-family-core-v1',SEED=847231,SIZE=32,RADIUS=2;
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const lerp=(a:number,b:number,t:number)=>a+(b-a)*t;
const angleLerp=(a:number,b:number,t:number)=>a+Math.atan2(Math.sin(b-a),Math.cos(b-a))*Math.min(1,t);
const hash=(x:number,z:number)=>{let n=Math.imul(x,374761393)^Math.imul(z,668265263)^Math.imul(SEED,1442695041);n=Math.imul(n^(n>>>13),1274126177);return((n^(n>>>16))>>>0)/4294967296};

const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fc7df);scene.fog=new THREE.Fog(0x9fc7df,75,190);
const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.05,500);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;document.querySelector('#game')!.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xdceeff,0x405044,2.2));const sun=new THREE.DirectionalLight(0xfff0d0,3);sun.position.set(35,70,25);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-90;sun.shadow.camera.right=90;sun.shadow.camera.top=90;sun.shadow.camera.bottom=-90;scene.add(sun);
const world=new THREE.Group(),actors=new THREE.Group();scene.add(world,actors);

class Player{root=new THREE.Group();velocity=new THREE.Vector3();onGround=true;speed=6.2;constructor(){const skin=new THREE.MeshStandardMaterial({color:0xc58f72,roughness:.8}),shirt=new THREE.MeshStandardMaterial({color:0x2d4962}),pants=new THREE.MeshStandardMaterial({color:0x24303a});const head=new THREE.Mesh(new THREE.SphereGeometry(.28,16,12),skin);head.position.y=1.72;const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.34,.65,5,10),shirt);torso.position.y=1.1;this.root.add(head,torso);for(const s of[-1,1]){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.11,.7,4,8),pants);leg.position.set(.14*s,.43,0);const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.09,.58,4,8),skin);arm.position.set(.43*s,1.1,0);arm.rotation.z=-.12*s;this.root.add(leg,arm)}this.root.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true}});actors.add(this.root)}}
const player=new Player();

class Chunks{loaded=new Map<string,THREE.Group>();changes:Record<string,string[]>={};key(x:number,z:number){return`${x},${z}`}coord(v:number){return Math.floor(v/SIZE)}
 build(cx:number,cz:number){const key=this.key(cx,cz),g=new THREE.Group();g.name=`chunk:${key}`;const ground=new THREE.Mesh(new THREE.BoxGeometry(SIZE,.35,SIZE),new THREE.MeshStandardMaterial({color:0x73975f,roughness:1}));ground.position.set(cx*SIZE+SIZE/2,-.18,cz*SIZE+SIZE/2);ground.receiveShadow=true;g.add(ground);const road=Math.abs(cx)%4===0||Math.abs(cz)%4===0;if(road){const r=new THREE.Mesh(new THREE.BoxGeometry(Math.abs(cx)%4===0?5:SIZE,.04,Math.abs(cz)%4===0?5:SIZE),new THREE.MeshStandardMaterial({color:0x3d4348}));r.position.set(cx*SIZE+SIZE/2,.02,cz*SIZE+SIZE/2);g.add(r)}const removed=this.changes[key]||[];for(let i=0;i<9;i++){if(hash(cx*17+i,cz*23-i)<=.56||road||removed.includes(`tree-${i}`))continue;const tree=new THREE.Group();tree.name=`tree-${i}`;tree.position.set(cx*SIZE+4+hash(cx+i,cz-i)*24,0,cz*SIZE+4+hash(cx-i,cz+i)*24);const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.18,.23,1.7,8),new THREE.MeshStandardMaterial({color:0x694b35}));trunk.position.y=.85;const crown=new THREE.Mesh(new THREE.SphereGeometry(1.15,9,7),new THREE.MeshStandardMaterial({color:0x3d7148}));crown.position.y=2.05;tree.add(trunk,crown);tree.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true}});g.add(tree)}if(cx===0&&cz===0)this.home(g);world.add(g);this.loaded.set(key,g)}
 home(g:THREE.Group){const h=new THREE.Group();h.name='home';h.position.set(10,0,10);const wall=new THREE.MeshStandardMaterial({color:0xe6ded0}),roofMat=new THREE.MeshStandardMaterial({color:0x7c4d3d}),dark=new THREE.MeshStandardMaterial({color:0x253746});const base=new THREE.Mesh(new THREE.BoxGeometry(9,3.6,7),wall);base.position.y=1.8;const roof=new THREE.Mesh(new THREE.ConeGeometry(6.4,2.4,4),roofMat);roof.rotation.y=Math.PI/4;roof.position.y=4.8;const door=new THREE.Mesh(new THREE.BoxGeometry(1.1,2.1,.08),dark);door.position.set(0,1.05,3.54);door.name='front-door';const win=new THREE.Mesh(new THREE.BoxGeometry(1.5,1.1,.08),dark);win.position.set(-2.3,1.7,3.54);win.name='window';h.add(base,roof,door,win);h.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true}});g.add(h)}
 stream(px:number,pz:number){const cx=this.coord(px),cz=this.coord(pz);for(const[k,g]of this.loaded){const[a,b]=k.split(',').map(Number);if(Math.abs(a-cx)>RADIUS||Math.abs(b-cz)>RADIUS){world.remove(g);this.loaded.delete(k)}}for(let x=cx-RADIUS;x<=cx+RADIUS;x++)for(let z=cz-RADIUS;z<=cz+RADIUS;z++)if(!this.loaded.has(this.key(x,z)))this.build(x,z)}
 harvest(pos:THREE.Vector3){const cx=this.coord(pos.x),cz=this.coord(pos.z),g=this.loaded.get(this.key(cx,cz));if(!g)return;let hit:THREE.Object3D|null=null,d=1.8;const candidates:THREE.Object3D[]=[];g.traverse(o=>{if(o.name.startsWith('tree-'))candidates.push(o)});for(const o of candidates){const q=o.getWorldPosition(new THREE.Vector3()),n=q.distanceTo(pos);if(n<d){d=n;hit=o}}if(hit!==null){const id=hit.name;this.changes[this.key(cx,cz)]??=[];this.changes[this.key(cx,cz)].push(id);g.remove(hit);saveNow()}}
}
const chunks=new Chunks();
let save:Save={version:1,player:{x:0,y:0,z:5,ry:0,mode:'tpp'},camera:{yaw:0,pitch:-.28,distance:7},changes:{}};
try{const raw=localStorage.getItem(SAVE_KEY);if(raw)save=JSON.parse(raw)}catch{}chunks.changes=save.changes;chunks.stream(save.player.x,save.player.z);player.root.position.set(save.player.x,save.player.y,save.player.z);player.root.rotation.y=save.player.ry;
let mode:Mode=save.player.mode,camYaw=save.camera.yaw,camPitch=save.camera.pitch,camDistance=save.camera.distance,targetYaw=camYaw,targetPitch=camPitch,targetDistance=camDistance;
function saveNow(){save={version:1,player:{x:player.root.position.x,y:player.root.position.y,z:player.root.position.z,ry:player.root.rotation.y,mode},camera:{yaw:camYaw,pitch:camPitch,distance:camDistance},changes:chunks.changes};localStorage.setItem(SAVE_KEY,JSON.stringify(save))}

const keys=new Set<string>();addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='f')mode='fpp';if(e.key.toLowerCase()==='c')mode='tpp'});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
let pointer:number|null=null,lastX=0,lastY=0;renderer.domElement.addEventListener('pointerdown',e=>{pointer=e.pointerId;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(pointer!==e.pointerId)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;targetYaw-=dx*.008;targetPitch=clamp(targetPitch-dy*.006,-1.15,.9)});renderer.domElement.addEventListener('pointerup',()=>pointer=null);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();targetDistance=clamp(targetDistance+e.deltaY*.008,2.2,13)},{passive:false});

const stick=document.querySelector('#stick') as HTMLElement,knob=document.querySelector('#knob') as HTMLElement;let joy={x:0,y:0},joyActive=false;const moveJoy=(e:PointerEvent)=>{if(!joyActive)return;const r=stick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=e.clientX-cx,y=e.clientY-cy,l=Math.hypot(x,y),m=43;if(l>m){x=x/l*m;y=y/l*m}joy={x:x/m,y:y/m};knob.style.transform=`translate(${x}px,${y}px)`};stick.addEventListener('pointerdown',e=>{joyActive=true;stick.setPointerCapture(e.pointerId);moveJoy(e)});stick.addEventListener('pointermove',moveJoy);stick.addEventListener('pointerup',()=>{joyActive=false;joy={x:0,y:0};knob.style.transform='translate(0,0)'});
(document.querySelector('#modeBtn') as HTMLButtonElement).onclick=()=>mode=mode==='tpp'?'fpp':'tpp';(document.querySelector('#jumpBtn') as HTMLButtonElement).onclick=()=>{if(player.onGround){player.velocity.y=7.2;player.onGround=false}};(document.querySelector('#interactBtn') as HTMLButtonElement).onclick=interact;
const prompt=document.querySelector('#prompt') as HTMLDivElement,status=document.querySelector('#status')!;let promptTimer=0;function say(t:string){prompt.textContent=t;prompt.classList.add('show');promptTimer=1.2}function nearest():THREE.Object3D|null{let best:THREE.Object3D|null=null,d=2.2,p=player.root.position;world.traverse(o=>{if(o.name==='front-door'||o.name==='window'||o.name.startsWith('tree-')){const q=o.getWorldPosition(new THREE.Vector3()),n=q.distanceTo(p);if(n<d){d=n;best=o}}});return best}function interact(){const o=nearest();if(!o){say('Nothing close enough');return}if(o.name.startsWith('tree-')){chunks.harvest(o.getWorldPosition(new THREE.Vector3()));say('Tree harvested — change saved')}else if(o.name==='front-door')say('Front door — interior system attaches here');else say('Interactable detected')}

const clock=new THREE.Clock();let autosave=0,lastCx=999,lastCz=999;
function input(){let x=joy.x,y=joy.y;if(keys.has('a')||keys.has('arrowleft'))x-=1;if(keys.has('d')||keys.has('arrowright'))x+=1;if(keys.has('w')||keys.has('arrowup'))y-=1;if(keys.has('s')||keys.has('arrowdown'))y+=1;const l=Math.hypot(x,y);return l>1?{x:x/l,y:y/l}:{x,y}}
function update(dt:number){const iv=input(),moving=Math.hypot(iv.x,iv.y)>.08;const forward=new THREE.Vector3(Math.sin(camYaw),0,Math.cos(camYaw)),right=new THREE.Vector3(Math.cos(camYaw),0,-Math.sin(camYaw));const dir=new THREE.Vector3().addScaledVector(right,iv.x).addScaledVector(forward,-iv.y);if(dir.lengthSq()){dir.normalize();const desired=Math.atan2(dir.x,dir.z);player.root.rotation.y=angleLerp(player.root.rotation.y,desired,dt*10);const speed=keys.has('shift')?9:6.2;player.velocity.x=dir.x*speed;player.velocity.z=dir.z*speed;if(mode==='tpp')targetYaw=angleLerp(targetYaw,player.root.rotation.y+Math.PI,dt*2.2)}else{player.velocity.x=lerp(player.velocity.x,0,dt*10);player.velocity.z=lerp(player.velocity.z,0,dt*10)}if(keys.has(' ')&&player.onGround){player.velocity.y=7.2;player.onGround=false}player.velocity.y-=18*dt;player.root.position.y+=player.velocity.y*dt;if(player.root.position.y<=0){player.root.position.y=0;player.velocity.y=0;player.onGround=true}player.root.position.x+=player.velocity.x*dt;player.root.position.z+=player.velocity.z*dt;const cx=chunks.coord(player.root.position.x),cz=chunks.coord(player.root.position.z);if(cx!==lastCx||cz!==lastCz){chunks.stream(player.root.position.x,player.root.position.z);lastCx=cx;lastCz=cz}
camYaw=angleLerp(camYaw,targetYaw,dt*12);camPitch=lerp(camPitch,targetPitch,dt*12);camDistance=lerp(camDistance,targetDistance,dt*12);const focus=player.root.position.clone();focus.y+=1.05;if(mode==='tpp'){const h=Math.cos(camPitch)*camDistance,pos=focus.clone();pos.x+=Math.sin(camYaw)*h;pos.y+=Math.sin(camPitch)*camDistance;pos.z+=Math.cos(camYaw)*h;const rayDir=pos.clone().sub(focus).normalize(),hits=new THREE.Raycaster(focus,rayDir,0,camDistance).intersectObjects(world.children,true),hit=hits.find(h=>h.object.name!=='ground');if(hit)pos.copy(focus).add(rayDir.multiplyScalar(Math.max(1.35,hit.distance-.2)));camera.position.lerp(pos,Math.min(1,dt*14));camera.lookAt(focus)}else{const eye=player.root.position.clone();eye.y+=1.55;camera.position.lerp(eye,Math.min(1,dt*18));const look=eye.clone();look.x+=Math.sin(targetYaw)*Math.cos(targetPitch)*8;look.y+=Math.sin(targetPitch)*8;look.z+=Math.cos(targetYaw)*Math.cos(targetPitch)*8;camera.lookAt(look)}
const near=nearest();if(near&&!moving&&!promptTimer)say(`USE · ${near.name.replace('front-door','Front door').replace('tree-','Tree ')}`);if(promptTimer>0){promptTimer-=dt;if(promptTimer<=0)prompt.classList.remove('show')} (document.querySelector('#modeBtn') as HTMLButtonElement).textContent=mode==='tpp'?'FPP':'TPP';autosave+=dt;if(autosave>2){autosave=0;saveNow()}status.textContent=`${mode.toUpperCase()} · chunk ${cx},${cz} · ${chunks.loaded.size} loaded`}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('beforeunload',saveNow);function loop(){requestAnimationFrame(loop);update(Math.min(clock.getDelta(),.05));renderer.render(scene,camera)}loop();